version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: kbg
      POSTGRES_PASSWORD: kbg
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  superset:
    image: apache/superset
    container_name: superset
    depends_on:
      - postgres
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      PYTHONPATH: /app/pythonpath
    volumes:
      - ./superset:/app/pythonpath
    ports:
      - "8088:8088"
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "

volumes:
  pgdata:
