"""initial schema

Revision ID: a027138a1298
Revises: 
Create Date: 2025-05-28 16:41:00.925856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a027138a1298'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('doa', sa.DateTime(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('semester', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seat_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ranking', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allotted_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rural_urban', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('non_ka_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_usn'), 'student', ['usn'], unique=True)
    op.create_table('achievement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('achievement_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('achievement_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('certificated_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['usn'], ['student.usn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_usn'), 'achievement', ['usn'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('sgpa', sa.Float(), nullable=True),
    sa.Column('backlog', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usn'], ['student.usn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_usn'), 'result', ['usn'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_usn'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_achievement_usn'), table_name='achievement')
    op.drop_table('achievement')
    op.drop_index(op.f('ix_student_usn'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
